# Generated by Django 3.0.4 on 2020-03-14 10:06

from django.db import migrations, models
import django.db.models.deletion
import notes.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20200314_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='image',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=notes.models.get_image_filename, verbose_name='Image')),
                ('note', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='notes.Note')),
            ],
        ),
    ]
