# Generated by Django 3.0.4 on 2020-03-14 11:33

from django.db import migrations, models
import notes.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20200314_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=notes.models.get_image_filename, verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, default='New Note', max_length=120),
        ),
    ]
