# Generated by Django 3.0.4 on 2020-03-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20200314_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='important',
            new_name='pinned',
        ),
    ]
