# Generated by Django 3.0.4 on 2020-03-15 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20200314_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created']},
        ),
    ]
