# Generated by Django 3.0.4 on 2020-03-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_auto_20200315_0758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created', 'pinned']},
        ),
    ]
